name: deploy
on:
  push:
    branches: [ master-pipeline ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build 
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./RestaurantAPI/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: upload artifact
        uses: actions/upload-artifact@v4.3.3
        with: 
         name: api-artifact
         path: ${{ env.DOTNET_ROOT }}/api

  deploy-dev: 
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: api-artifact
      - name: Azure WebApp deploy
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: "fs-restaurantapi-dev"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }} 

#  deploy-prod: 
#    runs-on: ubuntu-latest
#    needs: deploy-dev
#    environment: 
#      name: 'Prod'
#      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
#    steps:
#      - name: Download a Build Artifact
#        uses: actions/download-artifact@v4.1.7
#        with:
#          name: api-artifact
#      - name: Azure WebApp deploy
#        id: deploy-to-azure
#        uses: Azure/webapps-deploy@v3.0.1
#        with:
#          app-name: "fs-restaurantapi-prod"
#          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
